import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import HomePage from "./homePage";
import Works from "./works";
import Services from "./services";

import Contact from "./contact";
import Footer from "./Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Abdi Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <HomePage />
      <Services />
      <Works />
      <Contact />
      <Footer />
    </div>
  );
}
